// examples/next-mal-auth/src/app/Auth.tsx
"use client";
import { signIn, signOut, useSession } from "@animelist/auth-next/client";

export default function Auth() {
  const { user, isLoading } = useSession();

  return (
    <header className="bg-black">
      <div className="w-full flex flex-row mx-auto container p-4 justify-between items-center h-16">
        {user ? (
          <span className="text-white font-semibold text-lg cursor-pointer">
            Welcome {user.name}!
          </span>
        ) : (
          <span className="text-white font-semibold text-lg cursor-pointer">
            MyAnimeList - NextJS
          </span>
        )}

        <div className="ml-auto">
          {isLoading ? (
            <p className="text-white italic animate-pulse">Loading...</p>
          ) : user ? (
            <button
              onClick={signOut}
              className="rounded-md p-2 min-w-[100px] text-white shadow-md font-semibold bg-indigo-500 hover:bg-indigo-600"
            >
              Sign Out
            </button>
          ) : (
            <button
              onClick={signIn}
              className="rounded-md p-2 min-w-[100px] text-white shadow-md font-semibold bg-indigo-500 hover:bg-indigo-600"
            >
              Sign In
            </button>
          )}
        </div>
      </div>
    </header>
  );
}

// examples/sveltekit-mal-auth/src/routes/Auth.svelte
<script lang="ts">
	import { session, signIn, signOut } from '@animelist/auth-sveltekit/client';
</script>

<header class="bg-black">
	<div class="w-full flex flex-row mx-auto container p-4 justify-between items-center h-16">
		{#if $session.user}
			<span class="text-white font-semibold text-lg cursor-pointer">
				Welcome {$session.user.name}!
			</span>
		{:else}
			<span class="text-white font-semibold text-lg cursor-pointer"> MyAnimeList - Svelte </span>
		{/if}

		<div class="ml-auto">
			{#if $session.loading}
				<p class="text-white italic animate-pulse">Loading...</p>
			{:else if $session.user}
				<button
					on:click={signOut}
					class="rounded-md p-2 min-w-[100px] text-white shadow-md font-semibold bg-indigo-500 hover:bg-indigo-600"
				>
					Sign Out
				</button>
			{:else}
				<button
					on:click={signIn}
					class="rounded-md p-2 min-w-[100px] text-white shadow-md font-semibold bg-indigo-500 hover:bg-indigo-600"
				>
					Sign In
				</button>
			{/if}
		</div>
	</div>
</header>
